/// Format description module
module gfx.graal.format;

// module generated by formatgen.py

/// numeric format of texel channels
enum NumFormat
{
    uNorm,
    sNorm,
    uScaled,
    sScaled,
    uInt,
    sInt,
    uFloat,
    sFloat,
    sRgb,
}

/// description of a format
struct FormatDesc
{
    SurfaceType surfaceType;
    NumFormat numFormat;
    bool packed;
}

/// get the description of a format
FormatDesc formatDesc(in Format fmt) pure {
    return fmtDescs[cast(uint)fmt];
}

/// Format properties
struct FormatProperties {
    FormatFeatures linearTiling;
    FormatFeatures optimalTiling;
    FormatFeatures buffer;
}

/// Format features
enum FormatFeatures {
    sampledImage                = 0x0001,
    storageImage                = 0x0002,
    storageImageAtomic          = 0x0004,
    uniformTexelBuffer          = 0x0008,
    storageTexelBuffer          = 0x0010,
    storageTexelBufferAtomic    = 0x0020,
    vertexBuffer                = 0x0040,
    colorAttachment             = 0x0080,
    colorAttachmentBlend        = 0x0100,
    depthStencilAttachment      = 0x0200,
    blitSrc                     = 0x0400,
    blitDst                     = 0x0800,
    sampledImageFilterLinear    = 0x1000,

    framebuffer                 = 0x0380,
    blit                        = 0x0c00,
}

//## code_gen ##//
